# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      # Install Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.11' # Specify the version of Python you need

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Run tests
      - name: Run tests
        run: |
          python -m pytest <your_test_file.py>
